"""
Mẫu bổ sung cho 6 loại lỗi laptop mới.
Mỗi câu mô tả triệu chứng rõ ràng, tránh trùng lặp với nhãn hiện có.
"""

CATEGORY_META = {
    "wifi_network_issue": {
        "severity": "medium",
        "recommendation": "Kiểm tra driver Wi-Fi, reset mạng hoặc cập nhật firmware card mạng",
    },
    "touchpad_issue": {
        "severity": "medium",
        "recommendation": "Cập nhật driver touchpad, kiểm tra cài đặt hoặc thay module cảm ứng",
    },
    "usb_port_issue": {
        "severity": "medium",
        "recommendation": "Kiểm tra cổng USB, driver chipset và mainboard",
    },
    "webcam_issue": {
        "severity": "low",
        "recommendation": "Kiểm tra quyền camera, driver webcam hoặc thay module camera",
    },
    "performance_slow_issue": {
        "severity": "medium",
        "recommendation": "Kiểm tra RAM, ổ đĩa, malware và tối ưu phần mềm nền",
    },
    "storage_disk_issue": {
        "severity": "high",
        "recommendation": "Sao lưu dữ liệu, kiểm tra SMART ổ cứng và thay SSD/HDD nếu cần",
    },
}

EXTRA_SYMPTOMS = {
    "wifi_network_issue": [
        "laptop không tìm thấy mạng wifi nào quanh nhà",
        "máy em bật wifi nhưng không kết nối được dù nhập đúng mật khẩu",
        "wifi cứ tự ngắt rồi kết nối lại liên tục khi em đang học online",
        "biểu tượng wifi trên laptop báo không có internet",
        "máy nhận wifi nhưng tốc độ tải trang rất chậm so với điện thoại",
        "em quên mạng cũ rồi kết nối lại nhưng laptop vẫn không vào được",
        "laptop chỉ kết nối được mạng dây qua cổng lan còn wifi không hoạt động",
        "máy báo limited access dù đã kết nối đúng wifi nhà",
        "wifi laptop yếu, đứng cạnh router vẫn chỉ có một vạch",
        "sau khi cập nhật windows thì laptop không bật được wifi nữa",
        "máy em vào được wifi nhưng không ping được google",
        "laptop kết nối wifi xong vài phút là tự mất mạng",
        "driver wifi báo lỗi và không thể bật được card mạng không dây",
        "máy chỉ hiện mạng 2.4ghz mà không thấy mạng 5ghz của router",
        "em bật hotspot điện thoại mà laptop không nhận được sóng",
        "wifi laptop hay bị disconnect khi cắm sạc vào máy",
        "máy kết nối wifi công cộng được nhưng wifi nhà thì không",
        "laptop báo không có adapter wifi khả dụng trên thiết bị",
        "mạng wifi trên máy tính xách tay cứ báo đang xác thực mãi không xong",
        "em reset router rồi mà laptop vẫn không vào mạng được",
        "wifi laptop chỉ hoạt động khi tắt vpn còn bật vpn là mất mạng",
        "máy nhận wifi nhưng chrome báo dns probe finished no internet",
        "laptop không kết nối được wifi có dấu chấm than màu vàng",
        "sóng wifi trên laptop nhảy liên tục từ đầy xuống không",
        "máy em dùng wifi ở quán thì được về nhà thì laptop không vào mạng",
        "wifi adapter trên device manager hiện dấu chấm than",
        "laptop kết nối wifi nhưng không tải được file dù dung lượng nhỏ",
        "máy báo wifi connected nhưng ứng dụng nào cũng không truy cập mạng",
        "em gỡ driver wifi cài lại mà laptop vẫn không quét được mạng",
        "wifi laptop bị tắt xám và không bật lại được từ phím tắt",
        "máy kết nối wifi rồi báo no internet secured",
        "laptop hay mất wifi sau khi ngủ hoặc đóng nắp máy",
        "mạng wifi trên máy chỉ hoạt động một lúc rồi đứng hình",
        "em đổi tên wifi nhà xong laptop không nhận tên mạng mới",
        "wifi laptop rất chậm khi xem video call trên teams",
        "máy không kết nối được wifi ẩn dù đã nhập đúng ssid",
        "laptop báo lỗi default gateway not available khi dùng wifi",
        "wifi trên máy tính xách tay không bật được dù đã bật airplane mode off",
        "máy em kết nối wifi nhưng discord và zoom cứ báo mất kết nối",
        "laptop chỉ vào được một mạng wifi cũ còn mạng mới không hiện",
        "wifi laptop bị disable trong network settings và không enable được",
        "máy nhận wifi nhưng ip address bị 169.254 không có internet",
        "laptop kết nối wifi xong ping cao và lag khi chơi game online",
        "sau khi cài phần mềm diệt virus thì wifi laptop không hoạt động",
        "máy em dùng usb wifi dongle thì được còn wifi tích hợp thì không",
        "wifi laptop hay báo authentication problem khi nhập mật khẩu",
        "máy kết nối wifi nhưng không truy cập được trang nội bộ trường",
        "laptop không quét được hotspot từ điện thoại android",
        "wifi trên máy tính xách tay chỉ hoạt động khi khởi động lại liên tục",
        "máy báo wifi doesn't have a valid ip configuration",
        "em thử nhiều mạng khác nhau mà laptop vẫn không có internet qua wifi",
    ],
    "touchpad_issue": [
        "touchpad laptop em chạm vào không có phản ứng gì",
        "con trỏ trên touchpad nhảy lung tung khi em không chạm",
        "máy em không vuốt scroll được trên vùng cảm ứng",
        "touchpad chỉ nhận click trái còn click phải không hoạt động",
        "vùng cảm ứng laptop bị đơ, phải cắm chuột ngoài mới dùng được",
        "touchpad tự nhấn double click liên tục khi em di chuyển ngón tay",
        "máy em tắt touchpad trong settings rồi mà không bật lại được",
        "touchpad laptop phản hồi rất chậm, trễ vài giây mới di chuyển chuột",
        "gesture ba ngón trên touchpad không hoạt động nữa",
        "touchpad chỉ hoạt động ở một góc còn phần còn lại không nhận",
        "sau khi cập nhật driver touchpad thì vùng cảm ứng không dùng được",
        "máy em bật touchpad bằng phím fn nhưng vẫn không có con trỏ",
        "touchpad laptop bị khựng khi em gõ phím trên bàn phím",
        "con trỏ biến mất khi em chạm vào touchpad",
        "touchpad nhạy quá, chỉ để tay gần là chuột đã chạy",
        "máy em không zoom được bằng hai ngón trên touchpad",
        "touchpad laptop có tiếng lách cách khi bấm nhưng không di chuyển chuột",
        "vùng cảm ứng bị loạn, chạm một chỗ mà chuột nhảy chỗ khác",
        "touchpad không hoạt động sau khi laptop thức dậy từ chế độ ngủ",
        "máy báo touchpad disabled trong device manager",
        "touchpad em bị ẩm nước nhẹ nên không nhận cảm ứng",
        "scroll hai ngón trên touchpad bị ngược chiều",
        "touchpad laptop chỉ chạy khi cắm sạc còn dùng pin thì không",
        "máy em không tắt được touchpad khi dùng chuột ngoài",
        "touchpad bị rung nhẹ và con trỏ giật khi di chuyển",
        "vùng cảm ứng không nhận thao tác tap to click",
        "touchpad laptop có vết nứt nhỏ và không còn mượt",
        "máy em cài lại windows xong touchpad mất driver",
        "touchpad phản hồi sai, em vuốt xuống mà trang cuộn lên",
        "pin touchpad hết nên vùng cảm ứng không hoạt động trên laptop cũ",
        "touchpad bị đơ cứng khi mở nhiều tab chrome",
        "máy em không dùng được pinch zoom trên touchpad",
        "touchpad laptop nhận cảm ứng nhưng không click được",
        "con trỏ bị kẹt ở góc màn hình khi chạm touchpad",
        "touchpad không hoạt động dù đã enable trong control panel",
        "máy em thấy touchpad sáng đèn nhưng không di chuyển được chuột",
        "touchpad laptop bị lệch, chạm giữa mà chuột ở bên phải",
        "gesture chuyển desktop trên touchpad không còn hoạt động",
        "touchpad nhạy giật khi tay em hơi ẩm",
        "máy em phải bấm cứng touchpad mới nhận click",
        "touchpad không scroll được trong excel và word",
        "vùng cảm ứng laptop bị tối màu và không phản hồi",
        "touchpad tự bật lại sau khi em tắt trong settings",
        "máy em gắn chuột bluetooth xong touchpad bị conflict không dùng được",
        "touchpad chỉ hoạt động khi khởi động lại explorer",
        "driver synaptics trên laptop báo lỗi không khởi động",
        "touchpad laptop không nhận khi đeo găng tay hoặc film dày",
        "máy em không chỉnh được độ nhạy touchpad trong settings",
        "touchpad bị đơ sau khi cập nhật bios",
        "vùng cảm ứng máy tính xách tay không hoạt động dù chuột usb vẫn dùng được",
        "touchpad laptop em hỏng hoàn toàn, phải dùng chuột ngoài mọi lúc",
    ],
    "usb_port_issue": [
        "cổng usb laptop em cắm chuột vào không nhận thiết bị",
        "máy chỉ nhận usb ở một cổng còn các cổng khác không hoạt động",
        "ổ usb type c trên laptop không sạc và không truyền dữ liệu",
        "cắm usb vào máy thì windows báo device descriptor request failed",
        "cổng usb laptop lỏng, cắm vào là rớt liên tục",
        "máy em cắm ổ cứng di động usb nhưng không hiện trong this pc",
        "usb port chỉ nhận sạc mà không nhận flash drive",
        "laptop không nhận bàn phím cơ qua cổng usb",
        "cắm usb hub vào máy thì tất cả thiết bị đều không hoạt động",
        "cổng usb 3.0 trên laptop chạy chậm như usb 2.0",
        "máy báo usb device not recognized khi cắm tai nghe usb",
        "cổng usb bên trái laptop hỏng hoàn toàn không nhận gì",
        "em cắm usb wifi dongle mà laptop không cài được driver",
        "usb port hay bị ngắt kết nối khi di chuyển máy nhẹ",
        "laptop không nhận máy in qua cổng usb dù đã cài driver",
        "cắm usb vào máy nghe tiếng ting nhưng không thấy ổ đĩa",
        "cổng usb type c không xuất hình ra màn hình ngoài",
        "máy em cắm gamepad usb vào laptop không phản hồi",
        "usb port bị cháy mùi khét khi cắm thiết bị vào",
        "laptop nhận usb chậm, copy file tốc độ rất thấp",
        "cổng usb sau khi sửa mainboard thì không hoạt động",
        "máy báo power surge on usb port khi cắm ổ cứng",
        "usb port laptop không cấp điện cho thiết bị ngoài",
        "em thử nhiều cáp usb khác mà laptop vẫn không nhận",
        "cổng usb chỉ hoạt động khi khởi động lại máy",
        "laptop không nhận micro usb dù điện thoại vẫn sạc được",
        "cắm usb vào máy thì device manager hiện unknown device",
        "cổng usb 2.0 và 3.0 trên laptop đều không nhận chuột",
        "máy em cắm usb boot win nhưng không boot được từ usb",
        "usb port bị oxi hóa nên tiếp xúc kém",
        "laptop nhận usb rồi tự disconnect sau vài giây",
        "cổng usb cạnh bên phải máy chập chờn lúc nhận lúc không",
        "máy không nhận card reader qua cổng usb",
        "cắm usb vào laptop mà đèn báo trên thiết bị không sáng",
        "usb controller trong device manager báo lỗi code 43",
        "laptop không nhận webcam usb ngoài",
        "cổng usb type c chỉ sạc được một chiều cáp",
        "máy em cắm hai usb cùng lúc thì một cái bị ngắt",
        "usb port laptop không hoạt động sau khi cài lại windows",
        "cắm usb vào máy nghe tiếng kêu lạ từ cổng",
        "laptop không nhận ổ quang usb ngoài",
        "cổng usb bị cong chân nên không cắm chặt được",
        "máy nhận usb nhưng báo cần format dù ổ vẫn dùng được máy khác",
        "usb port trên laptop không nhận dock station",
        "em cắm usb vào cổng type c qua hub mà máy không thấy thiết bị",
        "laptop không nhận microphone usb",
        "cổng usb chỉ hoạt động khi tắt chế độ tiết kiệm pin",
        "máy báo usb malfunction khi cắm bất kỳ thiết bị nào",
        "usb port laptop em hỏng hết, phải dùng hub usb ngoài",
        "cắm usb vào máy thì safe removal icon không hiện",
        "laptop không nhận thiết bị usb sau khi update driver chipset",
    ],
    "webcam_issue": [
        "webcam laptop em mở zoom thì màn hình đen không thấy hình",
        "camera trên máy tính xách tay không được nhận trong device manager",
        "webcam báo lỗi camera in use by another application",
        "hình từ webcam laptop bị mờ và nhòe không rõ mặt",
        "máy em bật camera trong teams nhưng không hiện video",
        "webcam laptop chỉ hiện hình trắng xóa",
        "camera tích hợp không hoạt động sau khi cập nhật windows",
        "webcam laptop bị ngược hình, đầu ở dưới chân ở trên",
        "máy em không bật được đèn báo camera khi mở ứng dụng",
        "webcam có nhiều đốm sáng và sọc nhiễu trên hình",
        "camera laptop không hoạt động dù đã cấp quyền trong settings",
        "webcam bị delay, hình chậm hơn giọng nói khi họp online",
        "máy báo no camera found khi em gọi video",
        "webcam laptop chỉ hoạt động trong app camera còn zoom thì không",
        "camera bị lệch màu, da hiện xanh tím trên video call",
        "webcam laptop không nhận trong google meet",
        "máy em che nắp camera vật lý rồi mở mà vẫn không có hình",
        "webcam tự tắt sau vài phút khi em đang họp",
        "driver webcam báo lỗi code 10 cannot start",
        "camera laptop có tiếng rè kèm hình nhiễu",
        "webcam không hoạt động khi dùng pin nhưng cắm sạc thì được",
        "máy em cài lại driver camera mà webcam vẫn đen",
        "webcam laptop nhận nhưng hình bị crop chỉ thấy nửa mặt",
        "camera tích hợp bị rung hình khi em di chuyển laptop nhẹ",
        "webcam không bật được trong cài đặt privacy của windows",
        "máy báo webcam disconnected trong obs",
        "camera laptop hiện hình nhưng rất tối dù phòng sáng",
        "webcam bị freeze, hình đứng yên còn âm thanh vẫn chạy",
        "máy em test camera trong settings thì được mở discord thì không",
        "webcam laptop có vệt sọc ngang trên hình video",
        "camera không hoạt động sau khi tắt trong bios",
        "webcam laptop bị lỗi overexposed, hình quá sáng chói",
        "máy em không thấy tùy chọn camera khi gọi messenger",
        "webcam nhận hình nhưng không có micro tích hợp đi kèm",
        "camera laptop bị mờ do bụi bám trên lens",
        "webcam không hoạt động khi kết nối màn hình ngoài",
        "máy báo camera failed to start trong ứng dụng học online",
        "webcam laptop hiện hình đen trắng như camera hỏng cảm biến",
        "camera tích hợp bị nhòe khi phòng thiếu sáng",
        "webcam em không focus được, hình luôn mờ",
        "máy em bật camera trong windows hello nhưng không nhận khuôn mặt",
        "webcam laptop chỉ hoạt động ở độ phân giải thấp",
        "camera bị lật ngược khi dùng skype",
        "webcam không hoạt động sau khi cài phần mềm filter camera",
        "máy em thấy camera enabled nhưng preview vẫn đen",
        "webcam laptop có điểm đen cố định trên hình",
        "camera tích hợp không hoạt động dù micro vẫn thu âm bình thường",
        "webcam bị crash app khi bật video call",
        "máy em không dùng được camera cho bài thi online trên laptop",
        "webcam laptop hỏng hoàn toàn, phải mua webcam usb ngoài",
        "camera trên máy tính xách tay không lên hình dù đèn báo đã sáng",
    ],
    "performance_slow_issue": [
        "laptop em chạy rất chậm dù mới khởi động xong",
        "máy mở chrome lên là đơ vài chục giây mới phản hồi",
        "laptop lag giật khi em kéo cửa sổ hoặc chuyển tab",
        "máy em chạy fan to nhưng hiệu năng vẫn rất chậm",
        "task manager báo cpu luôn 90 phần trăm dù em không mở app nặng",
        "laptop chậm sau khi cập nhật windows mới nhất",
        "máy mở ứng dụng office rất lâu, icon quay mãi không vào",
        "laptop em bị đơ khi mở nhiều tab cùng lúc",
        "máy phản hồi chậm, gõ phím xong vài giây chữ mới hiện",
        "laptop chạy chậm dù ổ ssd còn nhiều dung lượng trống",
        "máy em thấy disk usage 100 phần trăm liên tục trong task manager",
        "laptop giật lag khi xem video youtube 1080p",
        "máy khởi động vào windows được nhưng sau đó mọi thao tác đều chậm",
        "laptop bị chậm sau khi cài thêm phần mềm diệt virus",
        "máy em chạy một app là các app khác đều bị treo theo",
        "laptop lag khi copy file trong ổ đĩa dù file nhỏ",
        "máy phản hồi chậm khi cắm màn hình ngoài",
        "laptop em ram 8gb nhưng máy báo đã dùng gần hết ram",
        "máy chậm dù em đã tắt hết chương trình khởi động cùng windows",
        "laptop bị giật hình khi scroll trang web",
        "máy em mở photoshop trên laptop bị lag không dùng được",
        "laptop chạy chậm hơn hẳn so với lúc mới mua",
        "máy đơ vài giây mỗi khi em click chuột",
        "laptop bị chậm khi cắm sạc và nhanh hơn khi dùng pin",
        "máy em thấy nhiều tiến trình lạ chiếm cpu trong task manager",
        "laptop lag khi chạy excel có file lớn",
        "máy phản hồi chậm sau khi ngủ đông và mở lại",
        "laptop bị stutter khi chơi game nhẹ trên máy",
        "máy em cài thêm ram nhưng laptop vẫn chậm như cũ",
        "laptop chậm khi kết nối bluetooth tai nghe",
        "máy mở file pdf lớn bị treo không phản hồi",
        "laptop bị lag do quá nhiều extension trên trình duyệt",
        "máy em dọn rác ổ đĩa rồi mà laptop vẫn chậm",
        "laptop phản hồi chậm khi có nhiều thông báo windows popup",
        "máy bị đơ khi windows update đang chạy nền",
        "laptop chậm dù nhiệt độ cpu không cao lắm",
        "máy em mở task manager cũng mất rất lâu",
        "laptop lag khi dùng zoom và chia sẻ màn hình",
        "máy chạy chậm sau khi nhiễm malware quảng cáo",
        "laptop bị giật khi di chuyển cửa sổ giữa hai màn hình",
        "máy em thấy memory compression chiếm nhiều ram",
        "laptop phản hồi chậm khi ổ đĩa gần đầy",
        "máy bị lag do driver đồ họa cũ chưa cập nhật",
        "laptop chậm khi index search của windows đang chạy",
        "máy em khởi động được windows nhưng vào desktop rất lâu",
        "laptop bị treo tạm thời khi mở start menu",
        "máy chạy chậm dù em đã reset windows mà vẫn lag",
        "laptop lag khi mở nhiều ứng dụng microsoft 365",
        "máy em thấy antimalware service executable chiếm cpu cao",
        "laptop phản hồi chậm khi sync onedrive đang chạy",
        "máy tính xách tay em dùng rất chậm, mở app nào cũng phải đợi lâu",
    ],
    "storage_disk_issue": [
        "ổ cứng laptop em phát tiếng tít tít khi đọc dữ liệu",
        "máy báo a disk read error occurred khi khởi động",
        "windows trên laptop báo ổ đĩa cần kiểm tra và sửa lỗi",
        "ssd laptop không hiện trong disk management",
        "máy em copy file vào ổ d thì báo delayed write failed",
        "ổ cứng báo smart failure predicted on hard disk",
        "laptop hay báo windows detected a hard disk problem",
        "máy không lưu được file mới dù ổ còn trống vài gb",
        "ổ ssd laptop bị bad sector, đọc file rất chậm",
        "máy em mở folder thì loading mãi không hiện file",
        "disk management báo ổ chưa allocate dù trước đó vẫn dùng được",
        "laptop báo operating system not found do ổ boot lỗi",
        "máy khởi động được nhưng hay báo repairing disk errors",
        "ổ cứng laptop bị kêu click click rồi máy đơ",
        "em chạy chkdsk thì báo nhiều sector bị hỏng",
        "ssd laptop mất partition sau khi mất điện đột ngột",
        "máy không format được ổ dù đã backup dữ liệu",
        "ổ đĩa laptop hiện raw thay vì ntfs",
        "máy em cắm ổ ssd mới nhưng laptop không nhận trong bios",
        "file trên laptop hay bị corrupt khi mở lại",
        "ổ cứng nóng bất thường khi chỉ đọc file nhẹ",
        "máy báo disk full dù em đã xóa nhiều file",
        "ssd laptop tụt tốc độ đọc ghi xuống rất thấp",
        "máy em không cài được windows lên ổ mới vì không nhận ổ",
        "ổ đĩa laptop bị disconnect tự nhiên trong khi dùng",
        "windows explorer hay not responding khi truy cập ổ dữ liệu",
        "máy báo the volume does not contain a recognized file system",
        "ổ ssd laptop báo 0 byte dung lượng trong this pc",
        "em nghe tiếng rẹt rẹt từ vùng ổ cứng khi máy chạy",
        "laptop hay báo cyclic redundancy check error khi copy file",
        "máy không boot được do ổ ssd hỏng firmware",
        "ổ đĩa bị khóa read only không ghi thêm file được",
        "máy em restore file từ recycle bin thì báo corrupt",
        "ssd laptop mất dữ liệu sau khi update firmware ổ",
        "disk management hiện ổ unallocated màu đen",
        "máy báo reboot and select proper boot device do mất ổ boot",
        "ổ cứng laptop phát tiếng kêu lớn rồi tắt máy",
        "em chạy crystal disk info thì ổ báo cảnh báo đỏ",
        "laptop không nhận ổ thứ hai sau khi thay ổ chính",
        "máy hay báo location is not available khi mở ổ d",
        "ổ ssd laptop bị freeze khi ghi file lớn",
        "windows trên máy báo error 0x80070017 khi cài từ usb",
        "máy em partition ổ bị mất nhãn drive letter",
        "ổ đĩa laptop có bad block khi test bằng victoria",
        "máy không defrag được vì ổ báo lỗi phần cứng",
        "ssd laptop không mount được sau khi rút nguồn đột ngột",
        "máy báo disk i/o error khi mở ứng dụng từ ổ d",
        "ổ cứng laptop em có tiếng kêu lạ và hay mất file",
        "máy em clone ổ sang ssd mới nhưng laptop không boot từ ổ mới",
        "ổ đĩa báo reallocated sectors count cao trong smart",
        "laptop hay báo your pc ran into a problem do lỗi ổ đĩa khi đọc dữ liệu",
    ],
}
